### ISSUE TITLE
/saf-auth service uses hardcoded class ZOWE instead of the class specified in the URL

### ISSUE THREAD

**Issue by plavjanik** [zowe/zss#244]
The https://github.com/zowe/zss/blob/master/c/authService.c is documented as:

```
A handler performing the SAF_AUTH check: checks if the user has the
specified access to the specified entity in the specified class

 URL format:
   GET .../saf-auth/<USERID>/<CLASS>/<ENTITY>/<READ|UPDATE|ALTER|CONTROL>
 Example: /saf-auth/PDUSR/FACILITY/CQM.CAE.ADMINISTRATOR/READ
 ```

but this fails with "Unexpected access level".

This format works:
```
GET .../saf-auth/<ENTITY>/<READ|UPDATE|ALTER|CONTROL>
```

Is it intentional? Is it possible to use a different resource class than ZOWE?

What are the possible ways how to authenticate? Basic auth works, is it possible to use the Zowe JWT token?

**Comment by ifakhrutdinov** [comment]
@plavjanik looks like only ZOWE is allowed and your error is caused by the class you put into the URL. Basically that comment is incorrect and needs to be changed.

As for the hardcoded class, I believe it was intentional. Allowing users to check any user against any class/profile may cause security issues. There are others layers of protection against this but we decided to keep the hardcoded class here too.

We can discuss workarounds based on what you're trying to achieve.

**Comment by 1000TurquoisePogs** [comment]
Closing because this is old and intentional as Irek said. If we want to make an API that allows different classes to be used, it should be possible but let's resurrect the conversation if needed.
