### ISSUE TITLE
ZSS unixfile/contents api inserts symbols whenever file is larger than 1MB

### ISSUE THREAD

**Issue by struga0258** [zowe/zss#657]
Seems like the ZSS unixfile/contents api keeps inserting symbols whenever the file is larger than 1MB. This has been tested with all different tags and encoded files and only happens when files are larger than 1MB.

**Comment by DivergentEuropeans** [comment]
@jordanfilteau1995 was kind enough to take a look at it. Possible workaround? He said:
The base64 encoded string that zss is producing is incorrect. There's some bug. Perhaps the working buffer isn't cleared between logic in a loop and artifacts are left behind. If you try to get the file using responseType=RAW instead of responseType=B64, the file is correct.

**Comment by Gautham-coder** [comment]
Issue tested by reporter and confirmed resolved.
